require('deheto/theme')
require('deheto/plugins')
require('deheto/maps')
require('deheto/mysets')
require('deheto/telescope')
require('deheto/treesitter')
require('deheto/lsp/init')
require('deheto/nvimtree')
